# Generated by Django 3.0.8 on 2020-07-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200726_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopparam',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=None, help_text='kg', max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='thickness',
            field=models.DecimalField(decimal_places=1, help_text='sm', max_digits=3),
        ),
        migrations.AlterField(
            model_name='productorderamount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
