# Generated by Django 3.0.8 on 2020-07-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200727_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='additional_utils',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='autonomous_work_time',
            field=models.TimeField(help_text='h:m'),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='cache_memory',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='dynamics',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='mic',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='os',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='physical_memory',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='processor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_params', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='ram',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='laptopparam',
            name='screen_resolution',
            field=models.CharField(max_length=30),
        ),
    ]
