# Generated by Django 3.0.8 on 2020-08-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200814_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productorderdetail',
            unique_together={('order', 'product')},
        ),
    ]
