# Generated by Django 3.0.8 on 2020-08-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200816_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
