# Generated by Django 3.0.8 on 2020-09-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200913_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_id',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
