# Generated by Django 3.0.8 on 2020-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('On receipt', 'On Receipt'), ('Bank Transaction', 'Bank Transaction'), ('Qiwi wallet', 'Qiwi Wallet')], default='On receipt', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('City courier delivery', 'City Courier Delivery'), ('Boxberry', 'Boxberry')], default='Pickup', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_id',
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
