# Generated by Django 3.0.8 on 2020-09-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200917_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorderdetail',
            options={'ordering': ['product__slug']},
        ),
        migrations.AddField(
            model_name='product',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
