# Generated by Django 3.0.8 on 2020-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200919_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['slug']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='lbl_is_popular',
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
