# Generated by Django 3.0.8 on 2020-09-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200923_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaptopParam',
            new_name='LaptopsParams',
        ),
    ]
