# Generated by Django 3.0.8 on 2020-09-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20200930_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_percent',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_value',
            new_name='discount_value',
        ),
    ]
