# Generated by Django 3.0.8 on 2020-09-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20200930_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaptopsParams',
            new_name='LaptopParams',
        ),
    ]
