# Generated by Django 3.0.8 on 2020-10-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20201007_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('On receipt', 'On Receipt'), ('Bank Transaction', 'Bank Transaction'), ('Qiwi wallet', 'Qiwi Wallet')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('Store pickup', 'Store Pickup'), ('City courier delivery', 'City Courier Delivery'), ('Pickup point', 'Pickup Point')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
