# Generated by Django 3.0.8 on 2020-12-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20201024_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Awaits payment', 'Awaits Payment'), ('Payed', 'Payed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('Store pickup', 'Store Pickup'), ('City courier delivery', 'City Courier Delivery'), ('Pickup point', 'Pickup Point')], default='Awaits payment', max_length=30),
        ),
    ]
