# Generated by Django 3.0.8 on 2020-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20201209_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Awaits payment', 'Awaits Payment'), ('Payed', 'Payed')], default='Awaits payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('Store pickup', 'Store Pickup'), ('City courier delivery', 'City Courier Delivery'), ('Pickup point', 'Pickup Point')], max_length=30, null=True),
        ),
    ]
