# Generated by Django 3.0.8 on 2020-12-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20201209_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('Store pickup', 'Store Pickup'), ('City courier delivery', 'City Courier Delivery'), ('Pickup point', 'Pickup Point')], default=None, max_length=30, null=True),
        ),
    ]
